#!/usr/bin/env python
# -*- coding: utf-8 -*-

from io import open
import os
import sys
print(sys.version)
sys.path.append('./source')
from conf import project

oldFil=os.path.join("build", "latex", "{}.tex".format(project))
newFil=os.path.join("build", "latex", "{}.tex-new".format(project))

def freplace(old, new):
    with open(oldFil, mode="rt", encoding="utf-8") as fin, open(newFil, mode="wt", encoding="utf-8") as fout:
        for line in fin:
            fout.write(line.replace(old, new))
    os.remove(oldFil)
    os.rename(newFil, oldFil)

freplace(r'\documentclass[letterpaper,10pt,english]{report}', r'''\pdfminorversion=7
\documentclass[letterpaper, 10pt, english]{report}''')

# This removes code generated by sphinx which causes on Ubuntu 16.04
# a  "LaTeX Error: Option clash for package geometry." because we
# overwrite the geometry settings.
freplace(r'\usepackage[margin=1in,marginparwidth=0.5in]{geometry}', '') # for Linux
freplace(r'\usepackage{geometry}', '')                                  # for OS X

freplace(r'\\maketitle',
        r'\\input{../../source/titlepage.tex} \\setcounter{page}{2}')

freplace(r'\\phantomsection\\label{index::doc}',
        r'\\phantomsection\\label{index::doc} \\clearpage')

freplace(r'\\begin{thebibliography}{1}',
        r'''\\chapter{References}
\\begin{thebibliography}{1}''')

freplace(r'\\begin{Verbatim}[',
        r'\\begin{Verbatim}[fontsize=\\footnotesize, ')

freplace(r'\\begin{longtable}{|l|l|}',
         r'\\begin{longtable}{|*{2}{p{\\dimexpr(\\linewidth-\\arrayrulewidth)/2-2\\tabcolsep-\\arrayrulewidth\\relax}|}}')
